/**
 * Probability spaces generated by named events (Devore ch. 2; STA237 "probability spaces, conditional
 * probability, independence"). Facts are statements — P(A) = 0.01, P(B | A) = 0.95, P(B | not A) = 0.02,
 * independent A, B, disjoint A, C — and P(…) of any event built with and / or / not (∩, ∪, Aᶜ, A')
 * or a conditional P(E | F) is solved from them.
 *
 * Method: k events cut the sample space into 2^k atoms; every fact is a linear equation in the atom
 * probabilities (P(E | F) = v ⇔ P(E ∩ F) − v·P(F) = 0; independence becomes linear once one marginal
 * is known, so it is added as soon as it can be). A probability is determined exactly when its
 * indicator lies in the row space of the system (Gauss–Jordan elimination) — otherwise MathLab says
 * that the facts do not determine it instead of guessing.
 */
import { Expr } from '../../math-core/ast';
import { EvalContext, EvalError, PROBFACT, expectNumber } from '../../math-core/builtins';
import { MathValue, scalar } from '../../math-core/values';
import { numberLatex, symbolLatex } from '../../math-core/symbolic/print';
import { visual } from '../../visualization/scene-model';

export type Fact =
  | { type: 'value'; event: Expr; given?: Expr; p: number }
  | { type: 'independent' | 'disjoint'; events: Expr[] };

export interface ProbFactValue {
  kind: 'probfact';
  fact: Fact;
  latex: string;
  certainty: 'exact';
  [k: string]: unknown;
}

type Call = Extract<Expr, { type: 'call' }>;
// not a type guard on purpose: several checks in a row must not narrow the expression to `never`
const isCall = (e: Expr, n: string): boolean => e.type === 'call' && e.callee.type === 'sym' && e.callee.name === n;
const argsOf = (e: Expr) => (e as Call).args;
const COMPLEMENT = /^(.*?)(?:'|ᶜ)$/u;

/** The event names an expression uses (A' and Aᶜ count as A). */
export function eventNames(e: Expr, out = new Set<string>()): Set<string> {
  if (e.type === 'sym') {
    if (e.name === 'Ω' || e.name === '∅') return out;
    const m = COMPLEMENT.exec(e.name);
    out.add(m ? m[1] : e.name);
  } else if (e.type === 'call' && e.callee.type === 'sym' && ['and', 'or', 'not', 'given'].includes(e.callee.name)) e.args.forEach((a) => eventNames(a, out));
  else if (e.type === 'bin' && e.op === '^' && e.right.type === 'sym' && e.right.name === 'c') eventNames(e.left, out);
  else throw new EvalError('an event is a name (A, B, …) combined with and / or / not, e.g. P(A and not B) or P(B | A)');
  return out;
}

/** Indicator of an event over the 2^k atoms (bit i of an atom = event names[i] occurs). */
function indicator(e: Expr, names: string[]): number[] {
  const m = 1 << names.length;
  const atoms = (f: (w: number) => boolean) => Array.from({ length: m }, (_, w) => (f(w) ? 1 : 0));
  const rec = (x: Expr): number[] => {
    if (x.type === 'sym') {
      if (x.name === 'Ω') return atoms(() => true);
      if (x.name === '∅') return atoms(() => false);
      const c = COMPLEMENT.exec(x.name);
      const i = names.indexOf(c ? c[1] : x.name);
      return atoms((w) => (((w >> i) & 1) === 1) !== !!c);
    }
    if (x.type === 'bin' && x.op === '^') return rec(x.left).map((v) => 1 - v);
    if (isCall(x, 'not')) return rec(argsOf(x)[0]).map((v) => 1 - v);
    if (isCall(x, 'and')) {
      const [a, b] = argsOf(x).map(rec);
      return a.map((v, i) => v * b[i]);
    }
    if (isCall(x, 'or')) {
      const [a, b] = argsOf(x).map(rec);
      return a.map((v, i) => Math.max(v, b[i]));
    }
    throw new EvalError("'|' (given) can only appear once, at the top: P(E | F)");
  };
  return rec(e);
}

export function eventLatex(e: Expr): string {
  const rec = (x: Expr, ctx: 'top' | 'and' | 'or'): string => {
    if (x.type === 'sym') {
      if (x.name === 'Ω') return '\\Omega';
      if (x.name === '∅') return '\\varnothing';
      const c = COMPLEMENT.exec(x.name);
      return c ? `${symbolLatex(c[1])}^{c}` : symbolLatex(x.name);
    }
    if ((x.type === 'bin' && x.op === '^') || isCall(x, 'not')) {
      const a = x.type === 'bin' ? x.left : argsOf(x)[0];
      return a.type === 'sym' ? `${rec(a, 'top')}^{c}` : `\\left(${rec(a, 'top')}\\right)^{c}`;
    }
    if (isCall(x, 'and')) return argsOf(x).map((a) => rec(a, 'and')).join(' \\cap ');
    if (isCall(x, 'or')) {
      const s = argsOf(x).map((a) => rec(a, 'or')).join(' \\cup ');
      return ctx === 'and' ? `\\left(${s}\\right)` : s;
    }
    if (isCall(x, 'given')) return `${rec(argsOf(x)[0], 'top')} \\mid ${rec(argsOf(x)[1], 'top')}`;
    return '?';
  };
  return rec(e, 'top');
}

export function factLatex(f: Fact): string {
  if (f.type === 'value') return `P\\left(${eventLatex(f.event)}${f.given ? ` \\mid ${eventLatex(f.given)}` : ''}\\right) = ${numberLatex(f.p, 6)}`;
  const list = f.events.map((e) => eventLatex(e)).join(',\\ ');
  return f.type === 'independent' ? `${list}\\ \\text{independent}` : `${list}\\ \\text{mutually exclusive}`;
}

/** Evaluate a parsed fact statement (data from the parser / the statement rule). */
export function evaluateFact(data: unknown, ctx: EvalContext): MathValue {
  const d = data as { kind: string; event?: Expr; value?: Expr; events?: Expr[] };
  let fact: Fact;
  if (d.kind === 'value') {
    const p = expectNumber(ctx.evaluate(d.value!));
    if (!(p >= 0 && p <= 1)) throw new EvalError('a probability is between 0 and 1');
    const ev = d.event!;
    fact = isCall(ev, 'given') ? { type: 'value', event: argsOf(ev)[0], given: argsOf(ev)[1], p } : { type: 'value', event: ev, p };
    eventNames(ev);
  } else {
    fact = { type: d.kind as 'independent' | 'disjoint', events: d.events! };
    d.events!.forEach((e) => eventNames(e));
  }
  return { kind: 'probfact', fact, latex: factLatex(fact), certainty: 'exact' } as unknown as MathValue;
}

// ------------------------------------------------------------------ the linear system

const TOL = 1e-10;

class System {
  rows: number[][] = [];
  rhs: number[] = [];
  private keys = new Set<string>();
  constructor(readonly m: number) {}
  add(row: number[], b: number, key?: string) {
    if (key) {
      if (this.keys.has(key)) return;
      this.keys.add(key);
    }
    this.rows.push(row);
    this.rhs.push(b);
  }
  /** Gauss–Jordan: reduced rows with pivots; throws when the facts contradict each other. */
  reduce(): { R: number[][]; b: number[]; piv: number[] } {
    const R = this.rows.map((r) => r.slice());
    const b = this.rhs.slice();
    const piv: number[] = [];
    let r = 0;
    for (let c = 0; c < this.m && r < R.length; c++) {
      let best = r;
      for (let i = r + 1; i < R.length; i++) if (Math.abs(R[i][c]) > Math.abs(R[best][c])) best = i;
      if (Math.abs(R[best][c]) < TOL) continue;
      [R[r], R[best]] = [R[best], R[r]];
      [b[r], b[best]] = [b[best], b[r]];
      const s = R[r][c];
      for (let j = 0; j < this.m; j++) R[r][j] /= s;
      b[r] /= s;
      for (let i = 0; i < R.length; i++) {
        if (i === r || Math.abs(R[i][c]) < TOL) continue;
        const f = R[i][c];
        for (let j = 0; j < this.m; j++) R[i][j] -= f * R[r][j];
        b[i] -= f * b[r];
      }
      piv.push(c);
      r++;
    }
    for (let i = r; i < R.length; i++) if (Math.abs(b[i]) > 1e-9) throw new EvalError('these probabilities contradict each other (no probability space satisfies all of them)');
    return { R: R.slice(0, r), b: b.slice(0, r), piv };
  }
}

/** c·p when it is determined by the system (c in the row space), else undefined. */
function determined(red: { R: number[][]; b: number[]; piv: number[] }, c: number[]): number | undefined {
  const v = c.slice();
  let val = 0;
  red.piv.forEach((col, k) => {
    const f = v[col];
    if (Math.abs(f) < TOL) return;
    for (let j = 0; j < v.length; j++) v[j] -= f * red.R[k][j];
    val += f * red.b[k];
  });
  if (v.some((x) => Math.abs(x) > 1e-8)) return undefined;
  return Math.abs(val) < 1e-13 ? 0 : +val.toPrecision(12);
}

export interface Space {
  names: string[];
  determined(e: Expr): number | undefined;
  /** probabilities of the atoms (undefined where not determined) */
  atoms: (number | undefined)[];
}

function subsets<T>(xs: T[], min: number): T[][] {
  const out: T[][] = [];
  for (let mask = 0; mask < 1 << xs.length; mask++) {
    const s = xs.filter((_, i) => (mask >> i) & 1);
    if (s.length >= min) out.push(s);
  }
  return out;
}

export function solveSpace(facts: Fact[], extra: Expr[] = []): Space {
  const set = new Set<string>();
  for (const f of facts) (f.type === 'value' ? [f.event, ...(f.given ? [f.given] : [])] : f.events).forEach((e) => eventNames(e, set));
  extra.forEach((e) => eventNames(e, set));
  const names = [...set];
  if (names.length > 6) throw new EvalError('at most 6 events in one probability space');
  const m = 1 << names.length;
  const sys = new System(m);
  const ind = (e: Expr) => indicator(e, names);
  sys.add(new Array(m).fill(1), 1);
  const indep: Expr[][] = [];
  for (const f of facts) {
    if (f.type === 'value') {
      if (f.given) {
        const ef = ind({ type: 'call', callee: { type: 'sym', name: 'and' }, args: [f.event, f.given] });
        const fv = ind(f.given);
        sys.add(ef.map((v, i) => v - f.p * fv[i]), 0);
      } else sys.add(ind(f.event), f.p);
    } else if (f.type === 'disjoint') {
      for (const [a, b] of subsets(f.events, 2).filter((s) => s.length === 2)) sys.add(ind(a).map((v, i) => v * ind(b)[i]), 0);
    } else indep.push(...subsets(f.events, 2));
  }
  let red = sys.reduce();
  // independence: P(∩S) = Π P(Aᵢ) is linear as soon as all marginals but one are known
  for (let round = 0; round < 8 && indep.length; round++) {
    const before = sys.rows.length;
    for (const S of indep) {
      const ms = S.map((e) => determined(red, ind(e)));
      const unknown = ms.map((v, i) => (v === undefined ? i : -1)).filter((i) => i >= 0);
      if (unknown.length > 1) continue;
      const cap = S.map(ind).reduce((a, b) => a.map((v, i) => v * b[i]));
      const key = S.map((e) => JSON.stringify(e, (k, v) => (k === 'span' ? undefined : v))).join('∩');
      if (unknown.length === 0) sys.add(cap, ms.reduce((a, b) => a! * b!, 1)!, key);
      else {
        const j = unknown[0];
        const k = ms.reduce((a, v, i) => (i === j ? a : a! * v!), 1)!;
        const aj = ind(S[j]);
        sys.add(cap.map((v, i) => v - k * aj[i]), 0, key);
      }
    }
    if (sys.rows.length === before) break;
    red = sys.reduce();
  }
  const atoms = Array.from({ length: m }, (_, w) => determined(red, Array.from({ length: m }, (_, i) => (i === w ? 1 : 0))));
  if (atoms.some((p) => p !== undefined && p < -1e-9)) throw new EvalError('these probabilities are impossible together (some outcome would get a negative probability)');
  return { names, atoms, determined: (e) => determined(red, ind(e)) };
}

// ------------------------------------------------------------------ queries

/** Facts visible to the statement (the document gives P(…) statements every fact as a dependency). */
export function factsOf(ctx: EvalContext): Fact[] {
  return (ctx.names?.() ?? [])
    .filter((n) => n.startsWith(PROBFACT))
    .map((n) => ctx.lookup(n) as unknown as ProbFactValue | undefined)
    .filter((v): v is ProbFactValue => v?.kind === 'probfact')
    .map((v) => v.fact);
}

const AND = (a: Expr, b: Expr): Expr => ({ type: 'call', callee: { type: 'sym', name: 'and' }, args: [a, b] });
const NOT = (a: Expr): Expr => ({ type: 'call', callee: { type: 'sym', name: 'not' }, args: [a] });
const n6 = (x: number) => numberLatex(x, 6);

/** P(E) or P(E | F) of events, solved from the facts. */
export function eventProbability(arg: Expr, ctx: EvalContext): MathValue {
  const facts = factsOf(ctx);
  const [E, F] = isCall(arg, 'given') ? [argsOf(arg)[0], argsOf(arg)[1]] : [arg, undefined];
  const space = solveSpace(facts, [arg]);
  const tex = `P\\left(${eventLatex(arg)}\\right)`;
  const missing = () =>
    new EvalError(
      facts.length
        ? `P(${[...eventNames(arg)].join(', ')} …) is not determined by the ${facts.length} fact${facts.length > 1 ? 's' : ''} given — state more, e.g. another probability or 'independent A, B'`
        : 'no probabilities are given: state facts such as P(A) = 0.3, P(B | A) = 0.9 in the worksheet',
    );
  let value: number;
  let derivation: string;
  if (F) {
    const den = space.determined(F);
    const num = space.determined(AND(E, F));
    if (den === undefined || num === undefined) throw missing();
    if (den === 0) throw new EvalError(`P(${eventLatex(F)}) = 0: cannot condition on an impossible event`);
    value = num / den;
    const total = totalProbability(F, space, facts);
    derivation = `${tex} = \\frac{P\\left(${eventLatex(AND(E, F))}\\right)}{P\\left(${eventLatex(F)}\\right)} = \\frac{${n6(num)}}{${n6(den)}}${total ? `, \\quad ${total}` : ''}`;
  } else {
    const v = space.determined(E);
    if (v === undefined) throw missing();
    value = v;
    derivation = totalProbability(E, space, facts) ?? tex;
  }
  const highlight = indicatorSafe(F ? AND(E, F) : E, space.names);
  return scalar(+value.toPrecision(12), {
    certainty: 'exact',
    evidence: `solved from ${facts.length} fact${facts.length === 1 ? '' : 's'} over the ${1 << space.names.length} outcomes of ${space.names.join(', ')} (linear algebra — the facts determine this probability)`,
    derivation,
    visuals: [visual('probtree', { names: space.names, atoms: space.atoms, highlight, given: F ? indicatorSafe(F, space.names) : undefined }, 'tree diagram', 'tree')],
  }) as MathValue;
}

function indicatorSafe(e: Expr, names: string[]) {
  try {
    return indicator(e, names);
  } catch {
    return undefined;
  }
}

/** P(B) = P(B | A) P(A) + P(B | Aᶜ) P(Aᶜ) when B is a single event and a first event A conditions it. */
function totalProbability(B: Expr, space: Space, facts: Fact[]): string | undefined {
  const cond = facts.find((f) => f.type === 'value' && f.given && JSON.stringify(strip(f.event)) === JSON.stringify(strip(B)) && f.given.type === 'sym') as Extract<Fact, { type: 'value' }> | undefined;
  if (!cond) return undefined;
  const A = cond.given!;
  const pA = space.determined(A);
  const pBA = space.determined(AND(B, A));
  const pBnA = space.determined(AND(B, NOT(A)));
  if (pA === undefined || pBA === undefined || pBnA === undefined || pA <= 0 || pA >= 1) return undefined;
  const b = eventLatex(B), a = eventLatex(A);
  return `P(${b}) = P(${b} \\mid ${a})P(${a}) + P(${b} \\mid ${a}^{c})P(${a}^{c}) = ${n6(pBA / pA)}\\cdot ${n6(pA)} + ${n6(pBnA / (1 - pA))}\\cdot ${n6(1 - pA)} = ${n6(pBA + pBnA)}`;
}

const strip = (e: Expr): unknown => JSON.parse(JSON.stringify(e, (k, v) => (k === 'span' ? undefined : v)));

/** Does the event expression mention only names that are not random variables / worksheet values? */
export function isEventQuery(arg: Expr, ctx: EvalContext): boolean {
  let names: Set<string>;
  try {
    names = eventNames(arg);
  } catch {
    return false;
  }
  return [...names].every((n) => ctx.lookup(n) === undefined);
}